matrix:
  include:
    - language: node_js
      nodejs: "lts/*"
      before_script:
        - cd nodejs
        - npm ci
    - language: java
      jdk: openjdk11
      before_script:
        - cd java
