git:
  depth: 1
matrix:
  include:
    - language: node_js
      nodejs: "lts/*"
      before_script:
        - cd nodejs
        - npm ci
      cache:
        directories:
          - $HOME/.npm
          - $HOME/.nvm
    - language: java
      jdk: openjdk11
      before_script:
        - cd java
      cache:
        directories:
          - $HOME/.m2
